/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Valeria
 */
public class FormExpresionesAritmeticas extends javax.swing.JFrame{

    /**
     * Creates new form Ventana1
     */
    public FormExpresionesAritmeticas() {
        
        initComponents();
        setLocationRelativeTo(null);
    }
    
    JFrame ventana = new JFrame();
    
    public void BorrarTodo(){
        
        archivotxt.setText("");
        infija.setText("");
        polaca.setText("");
        inversa.setText("");
        ventana.dispose();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivotxt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infija = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        polaca = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        inversa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        borrar = new javax.swing.JToggleButton();
        seleccionar_archivo = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Seleccionar el archivo con la expresion aritmetica a recorrer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 64, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        archivotxt.setColumns(20);
        archivotxt.setRows(5);
        jScrollPane1.setViewportView(archivotxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 428, 210));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Recorrido Infijo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Recorrido Polaco");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Recorrido Polaco Inverso");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, -1, -1));

        infija.setColumns(20);
        infija.setRows(5);
        jScrollPane3.setViewportView(infija);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 150, 260));

        polaca.setColumns(20);
        polaca.setRows(5);
        jScrollPane4.setViewportView(polaca);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 150, 260));

        inversa.setColumns(20);
        inversa.setRows(5);
        jScrollPane5.setViewportView(inversa);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 150, 260));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("REPRESENTACION DE ARBOL DE EXPRESIÓN ARITMÉTICA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 520, -1));

        borrar.setText("Borrar Todo");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel1.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 103, -1));

        seleccionar_archivo.setText("Seleccionar");
        seleccionar_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionar_archivoActionPerformed(evt);
            }
        });
        jPanel1.add(seleccionar_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 103, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 410));
        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 430, 260));
        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 420, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionar_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionar_archivoActionPerformed
        BorrarTodo();
        
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo_leer = fc.getSelectedFile();
        if (archivo_leer.getAbsolutePath().endsWith(".txt")) {
            int confirm = JOptionPane.showOptionDialog(null, "¿Está seguro que desea usar el arhivo: " + archivo_leer.getName() + " ?",
                         "Confirmación",
                         JOptionPane.YES_NO_OPTION,
                         JOptionPane.QUESTION_MESSAGE,
                         null,
                         new Object[] { "Sí", "No"},
                         "No");
            if (confirm == JOptionPane.YES_OPTION) {

                try{
                    FileReader fr = new FileReader (archivo_leer);
                    BufferedReader br = new BufferedReader(fr);
                    String text = "";
                    String line = "";

                    while(((line = br.readLine())!=null) ){
                        text += line;
                    }
                    //archivotxt.append("La expresion aritmetica es la siguiente:\n\n");
                    archivotxt.setText(text);
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente");

                    String cadena = archivotxt.getText();
                    ArbolBinario ABE = new ArbolBinario(cadena);
                    infija.setText(ABE.Imprimir(0));
                    polaca.setText(ABE.Imprimir(1));
                    inversa.setText(ABE.Imprimir(2));

                    int mostrarArbol;
                    mostrarArbol = JOptionPane.showOptionDialog(null, "¿Desea ver la representacion grafica del arbol de expresiones aritmeticas?",
                            "Confirmación",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            new Object[] { "Sí", "No"},
                            "No");
                    if (mostrarArbol == JOptionPane.YES_OPTION) {
                        
                        Lienzo objLienzo = new Lienzo(); 
                        Controlador objControlador = new Controlador(objLienzo, ABE);
                        objControlador.iniciar();
                        ventana.setLocation(0, 0);
                        ventana.getContentPane().add(objLienzo);
                        ventana.setDefaultCloseOperation(3);
                        ventana.setSize(900, 900);
                        ventana.setVisible(true);
                        
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al leer el archivo, por favor intenta de nuevo");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Solo se aceptan archivos tipo (.txt), por favor intentar de nuevo");
        }
    }//GEN-LAST:event_seleccionar_archivoActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        BorrarTodo();
    }//GEN-LAST:event_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormExpresionesAritmeticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormExpresionesAritmeticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormExpresionesAritmeticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormExpresionesAritmeticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormExpresionesAritmeticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea archivotxt;
    private javax.swing.JToggleButton borrar;
    private javax.swing.JTextArea infija;
    private javax.swing.JTextArea inversa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea polaca;
    private javax.swing.JButton seleccionar_archivo;
    // End of variables declaration//GEN-END:variables
}
